#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Organization
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      variables:
        page_subtitle: Manage your Organization(s)
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: city
          label: City

        - mData: state
          label: State

        - mData: country_code
          sType: table-image
          sClass: text-center
          label: Country

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: Active

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions

    add:
      components: ["select2", "wysihtml5", "validation", "bootstrap-switch", "jquery-file-upload-image"]
      blocks: ["address.book"]
      #scripts: ["views.courses.edit"]
      template: form.tpl
      variables:
        page_subtitle: Create a new Organization
    'edit/{id}':
      components: ["select2", "wysihtml5", "validation", "bootstrap-switch", "jquery-file-upload-image", "jquery-mask", "phone-field"]
      blocks: ["dropbox.upload", "address.book"]
      template: form.tpl
      variables:
        page_subtitle: Edit your Organization
models:
  me: Sysclass\Models\Organizations\Organization
