#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Organization
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      variables:
        page_subtitle: Manage your Organization(s)
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: city
          label: City

        - mData: state
          label: State

        - mData: country_code
          sType: table-image
          sClass: text-center
          label: Country

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: Active

        - mData: options
          sType: table-options
          sClass: text-center
          label: Options

    add:
      components: ["select2", "wysihtml5", "validation", "bootstrap-switch", "jquery-file-upload-image"]
      blocks: ["address.book"]
      #scripts: ["views.courses.edit"]
      template: form.tpl
      variables:
        page_subtitle: Create a new Organization
    'edit/{id}':
      components: ["select2", "wysihtml5", "validation", "bootstrap-switch", "jquery-file-upload-image", "jquery-mask", "phone-field"]
      blocks: ["dropbox.upload", "address.book", "organization.social.list"]
      scripts: ["views.institution.edit"]
      template: form.tpl
      variables:
        page_subtitle: Edit your Organization
blocks:
  organization.social.list:
    context:
      sAjaxSource: /module/institution/items/details/datatable
      datatable_fields:

        - mData: locale_code
          label: Language

        - mData: website
          label: Web Site

        - mData: facebook
          label: Facebook

        - mData: linkedin
          label: Linked In

        - mData: skype
          label: Skype

        - mData: googleplus
          label: Google+

        - mData: options
          sType: table-options
          sClass: text-center
          label: Options
models:
  me: Sysclass\Models\Organizations\Organization
  details: 
    class: Sysclass\Models\Organizations\OrganizationL10n
    findMethod : "findUnique"
    updateMethod: "save"
    acl:
      create:
        resource: Institution
        action: edit
      edit:
        resource: Institution
        action: edit
      delete:
        resource: Institution
        action: edit