widgets:
  messages.inbox:
    context:
      messages:
        ajax_source: "/module/messages/items/me/datatable"
        datatable_fields:
        - mData: from.name
          label: From

        - mData: subject
          label: Subject

        - mData: timestamp
          sType: unix-moment-since
          sClass: text-center
          label: Date
models:
  me: 
    class: Sysclass\Models\Messages\Message
    exportMethod: ["toFullArray", ["Groups", "Users"]]