#######################
# GENERAL DEFINITIONS #
#######################
blocks:
  roadmap.courses.edit:
    context:
      block_id: "roadmap_course"
models:
  courses:
    class: Sysclass\Models\Content\Program
    exportMethod: ["toFullArray", ["CourseClasses"]]
    exportParams: [null, true]
  #course-classes:
  #  class: Sysclass\Models\Courses\CourseClasses
  # exportMethod: ["toFullClassArray", ["Classe",]]
  #  acl:
  #    view: 
  #      resource: Courses
  #      action: view
  #    create:
  #      resource: Courses
  #      action: edit
  #    edit:
  #      resource: Courses
  #      action: edit
  #classes:
  #  class: Sysclass\Models\Content\Course
    #listMethod: findFull
  #  exportMethod: ["toFullArray", ["Lessons"]]
  #  acl:
  #    create:
  #      resource: Classes
  #      action: create
  #lessons:
  #  class: Sysclass\Models\Content\Unit
  #  exportMethod: ["toFullLessonArray", ["Contents", "Progress"]]

models:
  course:
    class: Sysclass\Models\Content\Course
    acl:
      create: 
        resource: Classes
        action: create
      edit:
        resource: Classes
        action: edit
      delete:
        resource: Classes
        action: delete
  periods:
    class: Sysclass\Models\Content\CoursePeriods
    exportMethod : ["toFullArray", ["Courses"]]
    #exportMethod: ["toFullArray", ["Avatars", "UserGroups"]]
    #findMethod: findFirstById
  content-progress:
    class: Sysclass\Models\Content\Progress\Content
    createMethod: createOrUpdate
    acl:
      create: 
        resource: Lessons
        action: take