#######################
# GENERAL DEFINITIONS #
#######################
blocks:
  roadmap.courses.edit:
    context:
      block_id: "roadmap_course"
models:
  courses:
    class: Sysclass\Models\Courses\Course
    exportMethod: ["toFullArray", ["Classes"]]
  course-classes:
    class: Sysclass\Models\Courses\CourseClasses
    exportMethod: ["toFullArray", ["Classe"]]
    acl:
      create:
        resource: Courses
        action: edit
      edit:
        resource: Courses
        action: edit
  classes:
    class: Sysclass\Models\Courses\CourseClasses
    #listMethod: findFull
    exportMethod: ["toFullArray", ["Lessons"]]
    acl:
      create:
        resource: Classes
        action: create
  periods:
    class: Sysclass\Models\Courses\CoursePeriods
    exportMethod: ["toFullArray", []]
  content-progress:
    class: Sysclass\Models\Courses\Contents\Progress
    createMethod: save
    acl:
      create:
        resource: Lessons
        action: take
    #listMethod: findFull
    #exportMethod: ["toFullArray", ["Lessons"]]
