#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Groups
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      variables:
        page_subtitle: Manage your user groups
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: description
          label: Description

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: "Active"

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions

    add:
      components: ["validation", "wysihtml5", "bootstrap-switch","select2"]
      blocks: ["messages.group.allow"]
      template: form.tpl
      #scripts: ["models.users", "views.users.add"]
      variables:
        page_subtitle: Create a new group
    'edit/{id}':
      components: ["validation", "wysihtml5", "bootstrap-switch","select2", "icheck"]
      blocks: ["messages.group.allow", "group.definition"]
      template: form.tpl
      scripts: ["views.groups.edit"]
      variables:
        page_subtitle: Edit a group
blocks:
  group.definition:
    context:
      static:
        block_id: "group-static-definition"
        datatable_fields:
          - mData: id
            sClass: text-center
            label: "#"

          - mData: name
            label: Name

          - mData: surname
            label: Surname

          - mData: email
            label: Email

          - mData: active
            sType: table-boolean
            sClass: text-center
            label: Active

          - mData: options
            sType: table-options
            sClass: text-center
            label: Actions
      dynamic:
        block_id: "group-dynamic-definition"
        datatable_fields:
          - mData: id
            sClass: text-center
            label: "#"

          - mData: name
            label: Name

          - mData: surname
            label: Surname

          - mData: email
            label: Email

          - mData: active
            sType: table-boolean
            sClass: text-center
            label: Active

models:
  me: Sysclass\Models\Users\Group
  dynamic: Sysclass\Models\Users\DynamicGroup
  non-users:
    class: Sysclass\Models\Users\UsersGroups
    listMethod: findNonGroupUsers
  users: 
    class: Sysclass\Models\Users\UsersGroups
    listMethod: findGroupUsers
    acl:
      delete:
        resource: groups
        action: edit
