#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Groups
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      variables:
        page_subtitle: Manage your groups
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: description
          label: Description

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: "Active"

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions

    add:
      components: ["validation", "wysihtml5", "bootstrap-switch"]
      blocks: ["messages.group.allow"]
      template: form.tpl
      #scripts: ["models.users", "views.users.add"]
      variables:
        page_subtitle: Create a new User
    'edit/{id}':
      components: ["validation", "wysihtml5", "bootstrap-switch"]
      blocks: ["messages.group.allow", "users.list.table"]
      template: form.tpl
      scripts: ["views.groups.edit"]
      variables:
        page_subtitle: Config and edit group info
models:
  me: Sysclass\Models\Users\Group
  users: 
    class: Sysclass\Models\Users\UsersGroups
    findMethod: findByGroupId