#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Knowledge Base
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      #scripts: ["models.users", "views.users.add"]
      variables:
        page_subtitle: View system KB questions
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: title
          label: Title

        - mData: question.user_name
          label: Login

        - mData: question.timestamp
          sType: unix-moment-since
          sClass: text-center
          label: Creation Date

        - mData: approved
          sType: table-boolean
          sClass: text-center
          label: Approved

        - mData: options
          sType: table-options
          sClass: text-center
          label: Options

    add:
      components: ["select2","validation", "bootstrap-switch"]
      template: form.tpl
      #scripts: ["models.users", "views.users.add"]
      variables:
        page_subtitle: Create a new KB entry
    'edit/:id':
      components: ["select2","validation", "bootstrap-switch"]
      template: form.tpl
      #scripts: ["models.users", "views.users.add"]
      variables:
        page_subtitle: Edit a KB entry
