#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    stylesheets: ["css/components"]
    variables:
      page_title: Tests
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      variables:
        page_subtitle: Manage your tests and exams
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: class
          label: Class

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: Active

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions
    add:
      components: ["select2", "validation", "bootstrap-switch"]
      template: form.tpl
      variables:
        page_subtitle: Create a new test
    'edit/:identifier':
      components: ["select2", "validation", "bootstrap-switch"]
      blocks:
      - "questions.list"
      - "test_execution.list":
          filter:
            test_id: ":identifier"
      template: form.tpl
      variables:
        page_subtitle: Edit your test info
    'open':
      components: ["select2", "validation", "bootstrap-switch"]
      template: open.tpl
      variables:
        page_subtitle: Edit your test info
    'execute':
      components: ["select2", "validation", "bootstrap-switch", "icheck"]
      scripts : ["tests.execute"]
      template: execute.tpl
      variables:
        page_subtitle: Edit your test info
blocks:
  test_execution.list.table:
    context:
      block_id: "users"
      ajax_source: "/module/tests_execution/items/me/datatable/%filter$s"
      datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: login
          label: Login

        - mData: extended_user_type
          label: "User Type"

        - mData: creation_time
          sType: unix-moment-since
          sClass: text-center
          label: User Since

        - mData: last_login
          sType: unix-moment-since
          sClass: text-center
          label: Last Login

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions

      "id": "1",
      "test_id": "10",
      "user_id": "2",
      "try_index": "1",
      "start_timestamp": "1437429703",
      "paused": "0",
      "pending": "0",
      "answers": null,
      "completed": "1437429763",
      "test": {
        "timelimit": "1",
        "test_repetition": "5"
      },
      "progress": {
        "started": "1437429703",
        "time_elapsed": 60,
        "expire_in": 1437429763,
        "invalidate": true
      },
      "options": {
        "edit": {
          "icon": "icon-edit",
          "link": "\/module\/tests_execution\/edit\/1",
          "class": "btn-sm btn-primary"
        },
        "remove": {
          "icon": "icon-remove",
          "class": "btn-sm btn-danger"
        }
      }
