#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    stylesheets: ["css/components"]
    variables:
      page_title: Reports 
      # BASE VALUES.. USED ON ALL ROUTES
  routes:
    'show/{identifier}':
      override-route: "edit"
      components: ["sprintf", "select2", "datatables"]
      template: show.tpl
      scripts: ["views.report.show"]
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      #blocks: ["group.add"]
      scripts: ["view"]
      variables:
        page_subtitle: Manage your reports
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: datasource.name
          sClass: text-center
          label: Type

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: Active

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions
    
    'edit/{id}':
      components: ["select2", "wysihtml5", "validation", "bootstrap-switch"]
      blocks: ["report.definition"]
      template: form.tpl
      scripts: ["views.report.form"]
      variables:
        page_subtitle: Configure your report 
models:
  me: 
    class: Sysclass\Models\Reports\Report
    exportMethod: ["toFullArray"]
  users:
    class: Sysclass\Models\Reports\User
    #exportMethod: ["toFullArray", ["Avatars", "UserGroups"]]
    #findMethod: findFirstById
reports:
  users:
    title: > 
      <i class="fa fa-users"></i>
      User List
    model: users
    fields:
      - name: id
        type: integer
        label: Id
        category: General
        default: true
        freeze: true
        mData: id
        sClass: text-center

      - name: name
        type: string
        label: Name
        category: General
        default: true
        mData: name

      - name: surname
        type: string
        label: Surname
        category: General
        mData: surname

      - name: email
        type: email
        label: Email
        category: General
        default: true
        mData: email

      - name: login
        type: string
        label: Login
        category: General
        mData: login

      - name: pending
        type: bool
        label: Pending aproval
        category: Extra
        mData: pending
        sType: table-boolean
        sClass: text-center

      - name: viewed_license
        type: bool
        label: License Viewed
        category: Extra
        mData: viewed_license
        sType: table-boolean
        sClass: text-center

      - name: active
        type: bool
        label: Active
        category: Extra
        mData: active
        sType: table-boolean
        sClass: text-center

      - name: how_did_you_know
        type: bool
        label: How did you know?
        category: Extra
        mData: how_did_you_know
        sType: table-boolean
        sClass: text-center

      - name: n_courses
        type: integer
        label: "# Enrolled programs"
        category: Enrollment
        mData: n_courses
        sClass: text-center

      - name: n_approved_courses
        type: integer
        label: "# Enrolled approved programs"
        category: Enrollment
        mData: n_approved_courses
        sClass: text-center

      - name: first_enrollment
        type: datetime
        label: "Date of first enroll"
        category: Enrollment
        mData: first_enrollment
        sType: datetime-moment
        sClass: text-center

      - name: last_enrollment
        type: datetime
        label: "Date of last enroll"
        category: Enrollment
        mData: last_enrollment
        sType: datetime-moment
        sClass: text-center

      - name: n_access
        type: integer
        label: "# times logged in"
        category: Access
        mData: n_access
        sClass: text-center

      - name: first_access
        type: datetime
        label: "Date of first access"
        category: Access
        mData: first_access
        sType: datetime-moment
        sClass: text-center

      - name: last_access
        type: datetime
        label: "Date of last access"
        category: Access
        mData: last_access
        sType: datetime-moment
        sClass: text-center

      - name: min_rating
        type: integer
        label: "minimum rate"
        category: Rating
        mData: min_rating
        sClass: text-center

      - name: max_rating
        type: integer
        label: "maximum rate"
        category: Rating
        mData: max_rating
        sClass: text-center

      - name: avg_rating
        type: float
        label: "Average rate"
        category: Rating
        mData: avg_rating
        sType: table-float1
        sClass: text-center

      - name: n_rating
        type: integer
        label: "# of content rated"
        category: Rating
        mData: n_rating
        sClass: text-center

      - name: n_content
        type: integer
        label: "# of content enrolled"
        category: Roadmap
        mData: n_content
        sClass: text-center

      - name: n_progress
        type: integer
        label: "# of started content"
        category: Roadmap
        mData: n_progress
        sClass: text-center

      - name: avg_progress
        type: float
        label: "Overall progress"
        category: Roadmap
        mData: avg_progress
        sType: table-percentage1
        sClass: text-center

      - name: avg_started_progress
        type: float
        label: "Overall started progress"
        category: Roadmap
        mData: avg_started_progress
        sType: table-percentage1
        sClass: text-center

    filters: 
    - id: email
      label: Email
      type: string
      no_invert: true
    
    - id: is_supplier
      label: Is Supplier
      type: integer
      input: radio
      values: {1: "Yes", 0: "No"}
      operators: [equal]
      no_invert: true
    datatable :
      fixedHeader: true
      sAjaxSource: /module/report/items/users/datatable
      buttons: []


      #aoColumns:
      #  pending:




      # language_id:
      #  birthday:
      #    name: birthday
      #    mData: birthday
      #    sType: datetime-moment
      #    sClass: text-center
      #    label: Birthday
      #  timezone:
      #    name: timezone
      #    mData: timezone
      #    #sType: datetime-moment
      #    sClass: text-center
      #    label: Timezone
      #  last_login:
      #    name: last_login
      #    mData: last_login
      #    sType: datetime-moment
      #    sClass: text-center
      #    label: Last Login
      #  #phone:
      #  is_supplier:
      #    name: is_supplier
      #    mData: is_supplier
      #    sType: table-boolean
      #    sClass: text-center
      #    label: Is Supplier
      #  supplier_name:
      #    name: supplier_name
      #    mData: supplier_name
      #    sClass: text-center
      #    label: Supplier Name
      #  cnpj:
      #    name: cnpj
      #    mData: cnpj
      #    sClass: text-center
      #    label: CNPJ
        #postal_code:
        #    mData: postal_code
        #    sClass: text-center
        #    label: Postal Code
        #street:
        #    mData: street
        #    sClass: text-left
        #    label: Address
        #street2:
        #    mData: street2
        #    sClass: text-left
        #    label: Address 2
        #street_number:
        #    mData: street_number
        #    sClass: text-center
        #    label: Street Number
        #district:
        #    mData: district
        #    sClass: text-left
        #    label: District
        #city:
        #    mData: city
        #    sClass: text-left
        #    label: City
        #state:
        #    mData: state
        #    sClass: text-left
        #    label: State
      #  country:
      #      mData: country
      #      sClass: text-left
      #      label: Country


