#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    stylesheets: ["css/components"]
    variables:
      page_title: Reports 
      # BASE VALUES.. USED ON ALL ROUTES
  routes:
    'view/{identifier}':
      components: ["validation", "select2", "datatables"]
      template: view.tpl
    manage:
      components: ["validation", "select2", "wysihtml5"]
      #base_scripts : ["plugins/fullcalendar/fullcalendar/gcal"]
      #scripts: ["views.manage"]
      template: manage.tpl
      variables:
        page_subtitle: View and manage system reports

models:
  me: 
    class: Sysclass\Models\Enrollments\Enroll
    exportMethod: ["toExtendArray", ["EnrollFields"]]
  users:
    class: Sysclass\Models\Users\User
    #exportMethod: ["toFullArray", ["Avatars", "UserGroups"]]
    #findMethod: findFirstById
reports:
  users:
    model: users
    fields: [id, name, surname, email, pending, viewed_license, active,  how_did_you_know]
    datafields:
      id:
          mData: id
          sClass: text-center
          label: "#"
      name:
          mData: name
          label: Name
      surname:
          mData: surname
          label: Surname
      email:
          mData: email
          label: Email
      login:
          mData: login
          label: Login
      pending:
          mData: pending
          sType: table-boolean
          sClass: text-center
          label: Pending aproval
      viewed_license:
          mData: viewed_license
          sType: table-boolean
          sClass: text-center
          label: License Viewed
      active:
          mData: active
          sType: table-boolean
          sClass: text-center
          label: Active
      how_did_you_know: 
          mData: how_did_you_know
          sType: table-array
          sClass: text-center
          label: How did you know?
