#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    stylesheets: ["css/components"]
    variables:
      page_title: Reports 
      # BASE VALUES.. USED ON ALL ROUTES
  routes:
    'show/{identifier}':
      override-route: "edit"
      components: ["sprintf", "select2", "datatables"]
      template: show.tpl
      scripts: ["views.report.show"]
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      #blocks: ["group.add"]
      scripts: ["view"]
      variables:
        page_subtitle: Manage your reports
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: datasource.name
          sClass: text-center
          label: Type

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: Active

        - mData: options
          sType: table-options
          sClass: text-center
          label: Options
    
    add:
      components: ["select2", "wysihtml5", "validation", "bootstrap-switch"]
      blocks: ["report.definition"]
      template: form.tpl
      scripts: ["views.report.form"]
      variables:
        page_subtitle: Configure your report 

    'edit/{id}':
      components: ["select2", "wysihtml5", "validation", "bootstrap-switch"]
      blocks: ["report.definition"]
      template: form.tpl
      scripts: ["views.report.form"]
      variables:
        page_subtitle: Configure your report 
models:
  me: 
    class: Sysclass\Models\Reports\Report
    exportMethod: ["toFullArray"]
  users:
    class: Sysclass\Models\Reports\User
  programs:
    class: Sysclass\Models\Reports\Program
    #exportMethod: ["toFullArray", ["Avatars", "UserGroups"]]
    #findMethod: findFirstById
reports:
  users:
    title: > 
      <i class="fa fa-users"></i>
      User List
    model: users
    fields:
      - name: id
        type: integer
        label: Id
        category: General
        default: true
        freeze: true
        mData: id
        sClass: text-center

      - name: name
        type: string
        label: First name
        category: General
        default: true
        mData: name

      - name: surname
        type: string
        label: Last name
        category: General
        mData: surname

      - name: email
        type: email
        label: Email
        category: General
        default: true
        mData: email

      - name: login
        type: string
        label: Login
        category: General
        mData: login

      - name: pending
        type: bool
        label: Aproval pending 
        category: General
        mData: pending
        sType: table-boolean
        sClass: text-center

      - name: viewed_license
        type: bool
        label: Viewed license 
        category: General
        mData: viewed_license
        sType: table-boolean
        sClass: text-center

      - name: active
        type: bool
        label: Active
        category: General
        mData: active
        sType: table-boolean
        sClass: text-center

      - name: how_did_you_know
        type: bool
        label: How did learn?
        category: Custom
        mData: how_did_you_know
        sType: table-boolean
        sClass: text-center

      - name: is_supplier
        type: bool
        label: Is Supplier?
        category: Custom
        mData: is_supplier
        sType: table-boolean
        sClass: text-center

      - name: n_courses
        type: integer
        label: "Programs registered"
        category: Registration
        mData: n_courses
        sClass: text-center

      - name: n_approved_courses
        type: integer
        label: "# Approved programs"
        category: Registration
        mData: n_approved_courses
        sClass: text-center

      - name: first_enrollment
        type: datetime
        label: "Date first registered"
        category: Registration
        mData: first_enrollment
        sType: datetime-moment
        sClass: text-center

      - name: last_enrollment
        type: datetime
        label: "Date last registered"
        category: Registration
        mData: last_enrollment
        sType: datetime-moment
        sClass: text-center

      - name: n_access
        type: integer
        label: "# of logins"
        category: Access
        mData: n_access
        sClass: text-center

      - name: first_access
        type: datetime
        label: "Date of first login"
        category: Access
        mData: first_access
        sType: datetime-moment
        sClass: text-center

      - name: last_access
        type: datetime
        label: "Date of last login"
        category: Access
        mData: last_access
        sType: datetime-moment
        sClass: text-center

      - name: min_rating
        type: integer
        label: "Minimum rate"
        category: Rating
        mData: min_rating
        sClass: text-center

      - name: max_rating
        type: integer
        label: "Maximum rate"
        category: Rating
        mData: max_rating
        sClass: text-center

      - name: avg_rating
        type: float
        label: "Average rate"
        category: Rating
        mData: avg_rating
        sType: table-float1
        sClass: text-center

      - name: n_rating
        type: integer
        label: "# of rates"
        category: Rating
        mData: n_rating
        sClass: text-center

      - name: n_content
        type: integer
        label: "# of programs registered"
        category: Roadmap
        mData: n_content
        sClass: text-center

      - name: n_progress
        type: integer
        label: "# of started programs"
        category: Roadmap
        mData: n_progress
        sClass: text-center

      - name: avg_progress
        type: float
        label: "Overall progress"
        category: Roadmap
        mData: avg_progress
        sType: table-percentage1
        sClass: text-center

      - name: avg_started_progress
        type: float
        label: "Overall started progress"
        category: Roadmap
        mData: avg_started_progress
        sType: table-percentage1
        sClass: text-center

      - name: n_tests_avaliable
        type: integer
        label: "# assigements available "
        category: assignments
        mData: n_tests_avaliable
        sClass: text-center

      - name: n_tests_tried
        type: integer
        label: "# Assigements done"
        category: Tests
        mData: n_tests_tried
        sClass: text-center

      - name: n_execution_tries
        type: integer
        label: "# Assigements attempts"
        category: Tests
        mData: n_execution_tries
        sClass: text-center

      - name: max_tries_in_test
        type: integer
        label: "Attempts allowed"
        category: Tests
        mData: max_tries_in_test
        sClass: text-center

      - name: all_tries_avg_score
        type: float
        label: "Average score of all tries"
        category: Tests
        mData: all_tries_avg_score
        sType: table-percentage1
        sClass: text-center

      - name: avg_user_score
        type: float
        label: "Average score of assigements"
        category: Tests
        mData: avg_user_score
        sType: table-percentage1
        sClass: text-center

      - name: n_total_pass
        type: integer
        label: "# Assigements passed"
        category: Tests
        mData: n_total_pass
        sClass: text-center

      - name: n_total_failed
        type: integer
        label: "# Assigements failed"
        category: Tests
        mData: n_total_failed
        sClass: text-center

    filters: 
    - id: email
      label: Email
      type: string
      no_invert: true
    
    - id: is_supplier
      label: Relationship
      type: integer
      input: radio
      values: {1: "Yes", 0: "No"}
      operators: [equal]
      no_invert: true
    datatable :
      fixedHeader: true
      sAjaxSource: /module/report/items/users/datatable
      buttons: []

      #aoColumns:
      #  pending:

      # language_id:
      #  birthday:
      #    name: birthday
      #    mData: birthday
      #    sType: datetime-moment
      #    sClass: text-center
      #    label: Birthday
      #  timezone:
      #    name: timezone
      #    mData: timezone
      #    #sType: datetime-moment
      #    sClass: text-center
      #    label: Timezone
      #  last_login:
      #    name: last_login
      #    mData: last_login
      #    sType: datetime-moment
      #    sClass: text-center
      #    label: Last Login
      #  #phone:
      #  is_supplier:
      #    name: is_supplier
      #    mData: is_supplier
      #    sType: table-boolean
      #    sClass: text-center
      #    label: Is Supplier
      #  supplier_name:
      #    name: supplier_name
      #    mData: supplier_name
      #    sClass: text-center
      #    label: Supplier Name
      #  cnpj:
      #    name: cnpj
      #    mData: cnpj
      #    sClass: text-center
      #    label: CNPJ
        #postal_code:
        #    mData: postal_code
        #    sClass: text-center
        #    label: Postal Code
        #street:
        #    mData: street
        #    sClass: text-left
        #    label: Address
        #street2:
        #    mData: street2
        #    sClass: text-left
        #    label: Address 2
        #street_number:
        #    mData: street_number
        #    sClass: text-center
        #    label: Street Number
        #district:
        #    mData: district
        #    sClass: text-left
        #    label: District
        #city:
        #    mData: city
        #    sClass: text-left
        #    label: City
        #state:
        #    mData: state
        #    sClass: text-left
        #    label: State
      #  country:
      #      mData: country
      #      sClass: text-left
      #      label: Country

  programs:
    title: > 
      <i class="fa fa-graduation-cap"></i>
      Programs
    model: programs
    fields:
        #`c`.`area_id` AS `area_id`,
        #`c`.`description` AS `description`,
        #`c`.`objectives` AS `objectives`,
        #`c`.`goals` AS `goals`,
        #`c`.`duration_units` AS `duration_units`,
        #`c`.`duration_type` AS `duration_type`,
        #`c`.`price_total` AS `price_total`,
        #`#`.`price_step_units` AS `price_step_units`,
        #`c`.`price_step_type` AS `price_step_type`,
        #`c`.`archive` AS `archive`,
        #`c`.`created` AS `created`,
        #`c`.`language_id` AS `language_id`,
        #`c`.`image_id` AS `image_id`,
      - name: id
        type: integer
        label: Id
        category: General
        default: true
        freeze: true
        mData: id
        sClass: text-center

      - name: name
        type: string
        label: Name
        category: General
        default: true
        mData: name

      #- name: coordinator.name
      #  type: string
      #  label: Coordinator Name
      #  category: General
      #  default: false
      #  mData: coordinator.name

      #- name: coordinator.surname
      #  type: string
      #  label: Coordinator SurName
      #  category: General
      #  default: false
      #  mData: coordinator.surname

      - name: active
        type: bool
        label: Active
        category: General
        mData: active
        sType: table-boolean
        sClass: text-center

      - name: n_users
        type: integer
        label: "# of registered Users"
        category: General
        mData: n_users
        sClass: text-center

      - name: n_courses
        type: integer
        label: "# of courses"
        category: General
        mData: n_courses
        sClass: text-center

    filters: 
    - id: name
      label: Name
      type: string
      no_invert: true
    
    - id: is_supplier
      label: Is Supplier
      type: integer
      input: radio
      values: {1: "Yes", 0: "No"}
      operators: [equal]
      no_invert: true
    datatable :
      fixedHeader: true
      sAjaxSource: /module/report/items/programs/datatable
      buttons: []