<script type="text/javascript">
	T_MODULE_PAGAMENTO_BOLETO_BASEDIR	= '{$T_MODULE_PAGAMENTO_BOLETO_BASEDIR}';
	T_MODULE_PAGAMENTO_BOLETO_BASELINK	= '{$T_MODULE_PAGAMENTO_BOLETO_BASELINK}';
	T_MODULE_PAGAMENTO_BOLETO_BASEURL	= '{$T_MODULE_PAGAMENTO_BOLETO_BASEURL}';

	_MODULE_PAGAMENTO_BOLETO_PROCESSED_FILE	= 'Detalhes do arquivo processado';
</script>