<script type="text/javascript">
	T_MODULE_PAGAMENTO_BASEDIR	= '{$T_MODULE_PAGAMENTO_BASEDIR}';
	T_MODULE_PAGAMENTO_BASELINK	= '{$T_MODULE_PAGAMENTO_BASELINK}';
	T_MODULE_PAGAMENTO_BASEURL	= '{$T_MODULE_PAGAMENTO_BASEURL}';

	_MODULE_PAGAMENTO_DELETE_PAYMENT_TYPE_CONFIRM_TITLE = '{$smarty.const._MODULE_PAGAMENTO_DELETE_PAYMENT_TYPE_CONFIRM_TITLE}';
	_MODULE_PAGAMENTO_DELETE_PAYMENT_TYPE_CONFIRM_TEXT = '{$smarty.const._MODULE_PAGAMENTO_DELETE_PAYMENT_TYPE_CONFIRM_TEXT}';

	$_xpayment_mod_data = {Mag_Json_Encode data=$T_PAGAMENTO_MOD_DATA};
</script>