#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Roles
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      blocks: ["roles.create.dialog"]
      scripts: ["views.roles.view"]
      variables:
        page_subtitle: Manage your Roles
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: Active

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions

    add: false
    'edit/:id': false

blocks:
  users.list.table:
    context:
      block_id: "users"
      ajax_source: "/module/users/items/me/datatable?block"
      datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: surname
          label: Surname

        - mData: login
          label: Login

        - mData: user_type
          label: "User Type"

        - mData: last_login
          sType: datetime-moment-since
          sClass: text-center
          label: User Since

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions


