#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    stylesheets: ["css/components"]
    variables:
      page_title: Courses
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      variables:
        page_subtitle: Manage your Courses
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: price
          sType: table-currency
          label: Price

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: Active

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions
    add:
      components: ["datepicker", "timepicker", "select2", "wysihtml5", "validation", "bootstrap-switch"]
      template: form.tpl
      variables:
        page_subtitle: Create a new course
    'edit/{id}':
      components: ["datepicker", "timepicker", "select2", "wysihtml5", "validation", "bootstrap-switch"]
      blocks: ["roadmap.classes", "roadmap.grouping", "users.list.table"]
      #blocks: ["roadmap.classes"]
      scripts: ["views.courses.edit"]
      template: form.tpl
      variables:
        page_subtitle: Edit your course info
