#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Advertising
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      #scripts: ["models.users", "views.users.add"]
      variables:
        page_subtitle: Manage your in page advertisings
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: placement
          label: Placement

        - mData: view_type
          label: View Type

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: Active

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions

    'edit/{id}':
      components: ["select2","validation", "bootstrap-switch", 'wysihtml5', "jquery-jcrop"]
      template: form.tpl
      stylesheets: ["css/components", "css/pages/timeline"]
      blocks: ["advertising.banners"]
      #scripts: ["models.users", "views.users.add"]
      variables:
        page_subtitle: Edit a advertising item
widgets:
  ads.leftbar.banner:
  ads.rightbar.banner:
    panel : true
models:
  me:
    class: Sysclass\Models\Advertising\Advertising
  content:
    class: Sysclass\Models\Advertising\Content
    #listMethod: "listByAdvertisingId"
    exportMethod: ["toFullArray", ["Files"]]
    acl:
      delete:
        resource: Advertising
        action: edit
