<?php 
$result = array(
	'data'	=> array(
		"sProcessing"	=> __DATATABLES_sProcessing,
		"sLengthMenu"	=> __DATATABLES_sLengthMenu,
		"sZeroRecords"	=> __DATATABLES_sZeroRecords,
		"sInfo"			=> __DATATABLES_sInfo,
		"sInfoEmpty"	=> __DATATABLES_sInfoEmpty,
		"sInfoFiltered"	=> __DATATABLES_sInfoFiltered,
//		"sInfoPostFix"	=> __DATATABLES_sInfoPostFix,
		"sSearch"		=> __DATATABLES_sSearch,
		"sUrl"			=> __DATATABLES_sUrl,
		"oPaginate"		=> array(
			"sFirst"	=> __DATATABLES_oPaginate_sFirst,
			"sPrevious"	=> __DATATABLES_oPaginate_sPrevious,
			"sNext"		=> __DATATABLES_oPaginate_sNext,
			"sLast"		=> __DATATABLES_oPaginate_sLast
		)
	),
	'description' => array(
		"sProcessing"	=> __DATATABLES_sProcessing,
		"sLengthMenu"	=> __DATATABLES_sLengthMenu,
		"sZeroRecords"	=> __DATATABLES_sZeroRecords,
		"sInfo"			=> __DATATABLES_sInfo,
		"sInfoEmpty"	=> __DATATABLES_sInfoEmpty,
		"sInfoFiltered"	=> __DATATABLES_sInfoFiltered,
		"sInfoPostFix"	=> __DATATABLES_sInfoPostFix,
		"sSearch"		=> __DATATABLES_sSearch,
		"sUrl"			=> __DATATABLES_sUrl,
		"oPaginate"		=> array(
			"sFirst"	=> __DATATABLES_oPaginate_sFirst,
			"sPrevious"	=> __DATATABLES_oPaginate_sFirst,
			"sNext"		=> __DATATABLES_oPaginate_sNext,
			"sLast"		=> __DATATABLES_oPaginate_sLast
		)
	
	)
);

return $result;
?>