<?php 
$result = array(
	'data'	=> array(
		"weekdays"		=> array(
			0 => __L10N_SUNDAY,
			1 => __L10N_MONDAY,
			2 => __L10N_TUESDAY,
			3 => __L10N_WEDNESDAY,
			4 => __L10N_THURSDAY,
			5 => __L10N_FRIDAY,
			6 => __L10N_SATURDAY
		)
	),
	'description' => array(
		"weekdays"		=> array(
			0 => __L10N_SUNDAY,
			1 => __L10N_MONDAY,
			2 => __L10N_TUESDAY,
			3 => __L10N_WEDNESDAY,
			4 => __L10N_THURSDAY,
			5 => __L10N_FRIDAY,
			6 => __L10N_SATURDAY
		)
	)
);

return $result;
?>