#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Languages
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      blocks: ["translate.edit.dialog"]
      scripts: ["models.translate", "views.translate.view"]
      variables:
        page_subtitle: View system languages
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: surname
          label: Surname

        - mData: login
          label: Login

        - mData: pending
          sType: table-boolean
          sClass: text-center
          label: Pending aproval

        - mData: viewed_license
          sType: table-boolean
          sClass: text-center
          label: License Viewed

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: Active

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions

    add:
      components: ["select2","validation"]
      template: form.tpl
      scripts: ["models.translate", "views.translate.add"]
      variables:
        page_subtitle: View system languages
    'edit/{id}':
      components: ["select2","validation"]
      blocks: ["enroll.user.block"]
      template: form.tpl
      scripts: ["edit"]
      variables:
        page_subtitle: View system languages

models:
  me:
    class: Sysclass\Models\L18n\Language
    #exportMethod: ["toFullArray", ["Avatars", "UserGroups"]]
