#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Languages
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      #blocks: ["translate.edit.dialog"]
      #scripts: ["models.translate", "views.translate.view"]
      variables:
        page_subtitle: View system languages
      context:
        datatable_fields:
        - mData: code
          sClass: text-center
          label: Code

        - mData: country_image
          sType: table-image
          sClass: text-center
          label: Country

        - mData: name
          label: English Name

        - mData: local_name
          label: Local Name

        - mData: rtl
          sType: table-boolean
          sClass: text-center
          label: RTL

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: Active

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions

    add:
      components: ["select2","validation"]
      template: form.tpl
      scripts: ["models.translate", "views.translate.add"]
      variables:
        page_subtitle: View system languages
    'edit/{id}':
      components: ["select2","validation"]
      #blocks: ["enroll.user.block"]
      template: form.tpl
      #scripts: ["edit"]
      variables:
        page_subtitle: View system languages

models:
  me:
    class: Sysclass\Models\I18n\Language
