#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Lessons
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      variables:
        page_subtitle: Manage your Lessons
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: class
          label: Class

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: Active

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions
    add:
      components: ["select2", "validation", "bootstrap-switch"]
      template: form.tpl
      variables:
        page_subtitle: Create a new lessons
    'edit/:id':
      components: ["validation", "bootstrap-switch", "jquery-file-upload", "select2"]
      #blocks: ["permission.add", "users.list.table", "roadmap.courses.edit"]
      #scripts: ["views.courses.edit"]
      scripts: ["views.lessons.edit"]
      template: form.tpl
      variables:
        page_subtitle: Edit your lesson info
