#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Users
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      #blocks: ["group.add"]
      scripts: ["view"]
      variables:
        page_subtitle: Manage your users
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: surname
          label: Surname

        - mData: email
          label: Email

        - mData: pending
          sType: table-boolean
          sClass: text-center
          label: Pending aproval

        - mData: viewed_license
          sType: table-boolean
          sClass: text-center
          label: License Viewed

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: Active

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions

    add:
      components: ["select2","validation", "bootstrap-switch","pwstrength"]
      template: form.tpl
      scripts: ["views.form.users"]

      variables:
        page_subtitle: Create a new User
    'edit/{id}':
      components: ["select2","validation", "bootstrap-switch","pwstrength"]
      #blocks: ["enroll.user.block"]
      blocks: ["users.details", "address.book"]
      template: form.tpl
      scripts: ["views.form.users"]
      variables:
        page_subtitle: Config and edit user info
    profile:
      components: ["select2","validation","datepicker","pwstrength", "jquery-mask", "jquery-jcrop"]
      blocks: ["address.book"]
      stylesheets: ["css/pages/profile"]
      base_scripts: ["scripts/ui.menu.translate"]
      scripts: ["views.profile"]
      override-route: "edit"
      template: profile.tpl
      variables:
        page_title: Your Profile
        page_subtitle: See your profile info, change your password and more.

blocks:
  users.list.table:
    context:
      block_id: "users"
      ajax_source: "/module/users/items/me/datatable?block"
      datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: surname
          label: Surname

        - mData: login
          label: Login

        - mData: user_type
          label: "User Type"

        - mData: last_login
          sType: datetime-moment-since
          sClass: text-center
          label: User Since

models:
  me:
    class: Sysclass\Models\Users\User
    exportMethod: ["toFullArray", ["Avatars", "UserGroups"]]
    findMethod: findFirstById