dashboard:
    rows:
        0:
            1:
                weight:
                    lg: 12
                    md: 12
                    sm: 12
                    xs: 12
    widgets:
        1: ["dashboard.linkable.view"]
    sortable: false
    resources:
        users.overview.notification.order: ["courses", "tutoria", "calendar", "advisor", "tests"]
        dashboard.linkable.order: ["institution", "areas", "courses", "classes", "lessons", "tests", "questions", "news", "users"]
        dashboard.linkable.groups.order: ["administration", "content", "users", "communication", "not_classified"]
