dashboard:
    rows:
        0:
            1:
                weight:
                    lg: 8
                    md: 8
                    sm: 12
                    xs: 12
            2:
                weight:
                    lg: 4
                    md: 4
                    sm: 12
                    xs: 12

        1:
            3:
                weight:
                    lg: 12
                    md: 12
                    sm: 12
                    xs: 12
    widgets:
        1: ["users.overview", "ads.leftbar.banner", "notification.lastest", "courses.overview", "news.latest" ]
        2: ["institution.overview", "advisor.chat", "payment.overview", "ads.rightbar.banner", "messages.contactus", "messages.help", "messages.improvements"]
        3: ["calendar"]
        #1: ["users.overview"]
        #2: []
        #3: []
    sortable: false
    resources:
        layout.sections.topbar: ["users", "dashboard"]
        users.overview.notification.order: ["users", "courses", "kbase", "calendar", "advisor", "tests"]
