dashboard:
    rows:
        0:
            1:
                weight:
                    md: 9
                    sm: 12
                    xs: 12
            2:
                weight:
                    md: 3
                    sm: 12
                    xs: 12

        1:
            3:
                weight:
                    md: 12
                    sm: 12
                    xs: 12
    widgets:
        1: ["users.overview", "ads.leftbar.banner", "notification.lastest", "courses.overview", "news.latest" ]
        #2: ["institution.overview", "advisor.chat", "payment.overview", "ads.rightbar.banner", "messages.contactus", "messages.help", "messages.improvements"]
        2: ["institution.overview", "payment.overview", "ads.rightbar.banner", "messages.contactus", "messages.help", "messages.improvements"]
        3: ["calendar"]
        #1: ["content.overview"]
        #2: []
        #3: []
    sortable: false
    resources:
        users.overview.notification.order: ["users", "courses", "kbase", "calendar", "advisor", "tests"]
