dashboard:
    rows:
        0:
            1:
                weight:
                    lg: 3
                    md: 3
                    sm: 12
                    xs: 12
            2:
                weight:
                    lg: 9
                    md: 9
                    sm: 12
                    xs: 12
    widgets:
        #1: ["users.overview", "ads.leftbar.banner", "courses.overview"]
        #2: ["institution.overview", "advisor.chat", "ads.rightbar.banner"]
        1: ["advisor.queue.filter"]
        2: ["advisor.queue.list"]
    sortable: false
    resources:
        layout.sections.topbar: ["messages", "forum"]
        users.overview.notification.order: ["users", "courses", "kbase", "calendar", "advisor", "tests"]
