#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: User Types
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      variables:
        page_subtitle: Manage your user types
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: description
          label: Description

        - mData: active
          sType: table-boolean
          sClass: text-center
          label: "Active"

        - mData: options
          sType: table-options
          sClass: text-center
          label: Actions
    add: false
#    add:
#      components: ["validation", "wysihtml5"]
#      template: form.tpl
      #scripts: ["models.users", "views.users.add"]
#      variables:
#        page_subtitle: Create a new user type

    'edit/:id':
      components: ["validation", "wysihtml5"]
      template: form.tpl
      #scripts: ["models.users", "views.users.add"]
      variables:
        page_subtitle: Config and edit user type info

