#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Calendar Events
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    manage:
      components: ["fullcalendar", "validation", "select2", "wysihtml5", "datepicker", "timepicker"]
      base_scripts : ["plugins/fullcalendar/fullcalendar/gcal"]
      scripts: ["views.manage"]
      template: manage.tpl
      variables:
        page_subtitle: Manage your calendar events
