#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Events
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    manage:
      components: ["fullcalendar", "validation", "select2", "wysihtml5", "datepicker", "timepicker"]
      base_scripts : ["plugins/fullcalendar/fullcalendar/gcal"]
      scripts: ["views.manage"]
      template: manage.tpl
      variables:
        page_subtitle: Manage your events
    "event-source/add":
      components: ["validation", "wysihtml5"]
      #blocks: ["messages.eventtypes.allow"]
      template: event-source.tpl
      #scripts: ["models.users", "views.users.add"]
      variables:
        page_subtitle: Create a new Event Source
models:
  me:
    class: Sysclass\Models\Calendar\Event
    exportMethod: ["toFullArray", []]
  "event-sources": Sysclass\Models\Calendar\Sources