<?php 
define("__DATATABLES_sProcessing", "Processando");
define("__DATATABLES_sLengthMenu", "Mostrando _MENU_ registros por página");
define("__DATATABLES_sZeroRecords", "Nenhum registro encontrado");
define("__DATATABLES_sInfo", "Mostrando de _START_ até _END_ de um total de _TOTAL_ registros");
define("__DATATABLES_sInfoEmpty", "Nenhum registro encontrado");
define("__DATATABLES_sInfoFiltered", "(filtrado de um total de _MAX_ registros)");
define("__DATATABLES_sInfoPostFix", "");
define("__DATATABLES_sSearch", "Pesquisa");
//	"sUrl"			=> "sUrl",
define("__DATATABLES_oPaginate_sFirst", "Primeiro");
define("__DATATABLES_oPaginate_sPrevious", "Anterior");
define("__DATATABLES_oPaginate_sNext", "Próximo");
define("__DATATABLES_oPaginate_sLast", "Último");
?>