<?php
define("__L10N_JANUARY", "Janeiro"); 
define("__L10N_FEBRUARY", "Fevereiro"); 
define("__L10N_MARCH", "Mar&ccedil;o"); 
define("__L10N_APRIL", "Abril"); 
define("__L10N_MAY", "Maio"); 
define("__L10N_JUNE", "Junho"); 
define("__L10N_JULY", "Julho"); 
define("__L10N_AUGUST", "Agosto"); 
define("__L10N_SEPTEMBER", "Setembro");
define("__L10N_OCTOBER", "Outubro"); 
define("__L10N_NOVEMBER", "Novembro"); 
define("__L10N_DECEMBER", "Dezembro");

define("__L10N_SHORT_JANUARY", "Jan"); 
define("__L10N_SHORT_FEBRUARY", "Fev"); 
define("__L10N_SHORT_MARCH", "Mar"); 
define("__L10N_SHORT_APRIL", "Abr"); 
define("__L10N_SHORT_MAY", "Mai"); 
define("__L10N_SHORT_JUNE", "Jun"); 
define("__L10N_SHORT_JULY", "Jul"); 
define("__L10N_SHORT_AUGUST", "Ago"); 
define("__L10N_SHORT_SEPTEMBER", "Set");
define("__L10N_SHORT_OCTOBER", "Out"); 
define("__L10N_SHORT_NOVEMBER", "Nov"); 
define("__L10N_SHORT_DECEMBER", "Dez");

define("__L10N_SUNDAY", 'Domingo');
define("__L10N_MONDAY", 'Segunda-Feira');
define("__L10N_TUESDAY", 'Terça-Feira');
define("__L10N_WEDNESDAY", 'Quarta-feira');
define("__L10N_THURSDAY", 'Quinta-Feira');
define("__L10N_FRIDAY", 'Sexta-feira');
define("__L10N_SATURDAY", 'Sábado');

define("__L10N_SHORT_SUNDAY", "Dom"); 
define("__L10N_SHORT_MONDAY", "Seg"); 
define("__L10N_SHORT_TUESDAY", "Ter"); 
define("__L10N_SHORT_WEDNESDAY", "Qua"); 
define("__L10N_SHORT_THURSDAY", "Qui"); 
define("__L10N_SHORT_FRIDAY", "Sex"); 
define("__L10N_SHORT_SATURDAY", "Sáb"); 

define("__L10N_MIN_SUNDAY", "Dom"); 
define("__L10N_MIN_MONDAY", "Seg"); 
define("__L10N_MIN_TUESDAY", "Ter"); 
define("__L10N_MIN_WEDNESDAY", "Qua"); 
define("__L10N_MIN_THURSDAY", "Qui"); 
define("__L10N_MIN_FRIDAY", "Sex"); 
define("__L10N_MIN_SATURDAY", "Sáb");
?>