#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Calendar
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      variables:
        page_subtitle: Manage your calendar
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: description
          label: Description

        - mData: start_date
          sType: unix-moment-date
          label: Date

        - mData: type.name
          label: Type

        - mData: options
          sType: table-options
          sClass: text-center
          label: Options

    add:
      components: ["validation", "wysihtml5", "select2", "datepicker", "timepicker"]
      blocks: ["messages.events.allow"]
      template: form.tpl
      #scripts: ["models.users", "views.users.add"]
      variables:
        page_subtitle: Create a new Event
    'edit/:id':
      components: ["validation", "wysihtml5", "select2", "datepicker", "timepicker"]
      #blocks: ["messages.events.allow"]
      template: form.tpl
      #scripts: ["views.events.edit"]
      variables:
        page_subtitle: Config and edit events

