#######################
# GENERAL DEFINITIONS #
#######################
models:
  me: 
    class: Sysclass\Models\Dropbox\File
    exportMethod: ["toFullArray", ["Language"]]
    createMethod: addOrUpdate
    updateMethod: addOrUpdate
