#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    #base_scripts: ["scripts/crud.models.js"]
    variables:
      page_title: Event Type
  # BASE VALUES.. USED ON ALL ROUTES
  routes:
    view:
      components: ["select2","data-tables"]
      template: view.tpl
      variables:
        page_subtitle: Manage your event types
      context:
        datatable_fields:
        - mData: id
          sClass: text-center
          label: "#"

        - mData: name
          label: Name

        - mData: color
          label: Color

    add:
      components: ["validation", "wysihtml5"]
      blocks: ["messages.event_type.allow"]
      template: form.tpl
      #scripts: ["models.users", "views.users.add"]
      variables:
        page_subtitle: Create a new Event
    'edit/:id':
      components: ["validation", "wysihtml5"]
      blocks: ["messages.event_type.allow", "users.list.table"]
      template: form.tpl
      scripts: ["views.event_type.edit"]
      variables:
        page_subtitle: Config and edit event type

