#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    variables:
      page_title: Permissions

models:
  me: 
    class: Sysclass\Models\Acl\Resource
    acl:
      view:
        resource: Roles
        action: view