#######################
# GENERAL DEFINITIONS #
#######################
crud:
  # BASE VALUES.. USED ON ALL ROUTES
  base_route:
    variables:
      page_title: Permissions
models:
  me: Sysclass\Models\Acl\Resource